cliente = input("Digite o nome do cliente: ")
venc = input("Digite o dia de vencimento: ")
mvenc = input("Digite o mês de vencimento: ")
fatura =(input("Digite o valor da fatura: "))
print("Olá,",cliente)
print("A sua fatura com vencimento em",venc,"de",mvenc,"no valor de R$",fatura,"esta fechada.")